export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";
export const GET_AVAILABLE = "GET_AVAILABLE";
export const GET_AVAILABLE__SUCCESS = "GET_AVAILABLE__SUCCESS";
export const GET_AVAILABLE_FAILED = "GET_AVAILABLE_FAILED";
export const RESET_STATE = "RESET_STATE";
